version: '3.8'

services:


  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://samuelnihoul:aoethns24teuTT!@@db-primary:5432/renfo_pas_a_pas
      - VIDEO_STORAGE_PATH=/app/shared/videos
    volumes:
      - video_storage:/app/public/videos
    depends_on:
      - db-primary
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - 3001:3001

  # Primary Database
  db-primary:
    ports:
      - 5432:5432
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_USER=samuelnihoul
      - POSTGRES_PASSWORD=aoethns24teuTT!@
      - POSTGRES_DB=renfo_pas_a_pas
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge

volumes:
  postgres_primary_data:
  video_storage:
    driver: local
