version: '3.8'

services:
  # Load Balancer
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

  # Application (scaled to multiple instances)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://samuelnihoul:aoethns24teuTT!@@db-primary:5432/renfo-pas-a-pas
      - VIDEO_STORAGE_PATH=/app/shared/videos
    volumes:
      - video_storage:/app/public/videos
    depends_on:
      - db-primary
    networks:
      - app-network

  # Primary Database
  db-primary:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=samuelnihoul
      - POSTGRES_PASSWORD=aoethns24teuTT!@
      - POSTGRES_DB=renfo-pas-a-pas
    networks:
      - app-network
    restart: unless-stopped

  # Replica Database
  db-replica:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
      - ./db/postgresql.replica.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=samuelnihoul
      - POSTGRES_PASSWORD=aoethns24teuTT!@
      - POSTGRES_DB=renfo-pas-a-pas
    depends_on:
      - db-primary
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_primary_data:
  postgres_replica_data:
  video_storage:
    driver: local