version: '3.8'

services:
  # PostgreSQL Database
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=samuelnihoul
      - POSTGRES_PASSWORD=aoethns24teuTT!@
      - POSTGRES_DB=renfo-pas-a-pas
    networks:
      - app-network
    restart: unless-stopped

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://samuelnihoul:aoethns24teuTT!@@db:5432/renfo-pas-a-pas
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: